POST http://localhost:5000/account/create
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "mypassworsd"
}

###

POST http://localhost:5000/account/delete
Content-Type: application/json

{
  "username": "testuser",
  "password": "mypassword"
}
