POST http://localhost:5000/account/create
Content-Type: application/json

{
  "username": "testuser",
  "email": "test@example.com",
  "password": "mypassword"
}

###

DELETE  http://localhost:5000/account/delete
Content-Type: application/json

{
  "username": "testuser",
  "password": "mypassword"
}

###

POST http://localhost:5000/account/login
Content-Type: application/json

{
  "username": "testuser",
  "password":"password"
}

###

POST http://localhost:5000/post
Content-Type: application/json

{
  "title" : "title",
  "text" : "this is the text",
  "jwt" : ""
}

###
GET http://localhost:5000/localhost:5000/account/getId?userName=


###
GET http://localhost:5000/post/GET?userID